### ISSUE TITLE
runtime error: index out of range?

### ISSUE THREAD

**Issue by Kan18** [tmpim/juroku#1]
I am trying to use Juroku to convert an image and I get this error:

bash-4.4$ juroku fff.png
Image loaded, quantizing...
Image quantized, chunking and generating code...
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/tmpim/juroku.GenerateFrameChunk(0x415d360, 0xc0000560c0, 0x415d360, 0xc0000560c0, 0x0)
	$GOPATH/src/github.com/tmpim/juroku/cc.go:46 +0x7dc
main.main()
	$GOPATH/src/github.com/tmpim/juroku/cmd/juroku/juroku.go:144 +0x42b

The image in question is this: ![link](https://user-images.githubusercontent.com/24967425/64744069-51130d80-d4d0-11e9-96b1-65883b9cc4da.png)

**Comment by 1lann** [comment]
Sorry! I didn't notice this until now when I looked through my GitHub notifications.

I've reverted the master branch since it has experimental features that really shouldn't be there, those changes can be found in the `video` branch instead. The master branch should have working code now. I don't know why I was retarded enough to keep master in that state.
